# top-level test run
sim1:
	cd case_1 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim2:
	cd case_2 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim3:
	cd case_3 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim4:
	cd case_4 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim5:
	cd case_5 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim6:
	cd case_6 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim7:
	cd case_7 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

sim8:
	cd case_8 && $(MAKE) sim && $(MAKE) clean && $(MAKE) gen_rtl

simall: sim1 sim2 sim3 sim4 sim5 sim6 sim7 sim8