#! /usr/bin/env python3
import sys

from cmd_runner import CommandRunner
from utils.message import HRDAError

if __name__ == "__main__":
    runner =  CommandRunner()
    try:
        runner.run()
    except HRDAError:
        sys.exit(1)
