#! /usr/bin/env python3
import sys
import time

from cmd_runner import CommandRunner
from utils.message import HRDAError
from utils.env import HRDAEnv

if __name__ == "__main__":
    HRDAEnv.start_time = time.time()
    runner =  CommandRunner()

    try:
        runner.run()
    except HRDAError:
        sys.exit(1)
